### ISSUE TITLE
!tps Discord error and plugin crash

### ISSUE THREAD

**Issue by shplack** [jamesinaxx/FOMO#5]
```
11.05 07:07:48 [Server] ERROR One of the EventListeners had an uncaught exception
11.05 07:07:48 [Server] INFO java.lang.NullPointerException: null
11.05 07:07:48 [Server] INFO at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
11.05 07:07:48 [Server] INFO at com.jamesinaxx.fomo.Discord.Discord.CommandHandler(Discord.java:50) ~[?:?]
11.05 07:07:48 [Server] INFO at com.jamesinaxx.fomo.Discord.Discord.onMessageReceived(Discord.java:29) ~[?:?]
11.05 07:07:48 [Server] INFO at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:435) ~[?:?]
11.05 07:07:48 [Server] INFO at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[?:?]
11.05 07:07:48 [Server] INFO at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[?:?]
11.05 07:07:48 [Server] INFO at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[?:?]
11.05 07:07:48 [Server] INFO at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149) ~[?:?]
11.05 07:07:48 [Server] INFO at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122) ~[?:?]
11.05 07:07:48 [Server] INFO at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[?:?]
11.05 07:07:48 [Server] INFO at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:956) ~[?:?]
11.05 07:07:48 [Server] INFO at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:843) ~[?:?]
11.05 07:07:48 [Server] INFO at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:821) ~[?:?]
11.05 07:07:48 [Server] INFO at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:994) ~[?:?]
11.05 07:07:48 [Server] INFO at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
11.05 07:07:48 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
11.05 07:07:48 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
11.05 07:07:48 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
11.05 07:07:48 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
11.05 07:07:48 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
11.05 07:07:48 [Server] INFO at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
```

Error running `!tps` in Discord channel

**Comment by jamesinaxx** [comment]
Thank you for reporting this. Could you reply with the FOMO version you are using, your config.yml file (token hidden), and server version (eg. ```PaperMC 1.16.5 Build #709```), please? I will work on fixing this asap

**Comment by shplack** [comment]
paper_1_16_5_1239036
FOMO v0.4
config.yml
```
## FOMO by jamesinaxx
## token: The token from discordapi.com
## channel: The channel you would like the bot to watch and write to (id |
right click channel and press copy id, also remove quotes as this can cause
issues)
## prefix: The command prefix for the bot to listen for
token: xxxxxxxxx
channel: 700398388356841483
prefix: !

```

Den ons 12 maj 2021 06:24jamesina ***@***.***> skrev:

**Comment by jamesinaxx** [comment]
I think I figured out the issue,
If you could try putting quotes around the ! in your config file
It seems as though it is not getting it properly because it thinks it isn't a string or something
I will see what I can do to fix this for future!

**Comment by jamesinaxx** [comment]
Closing this issue for now. Re-open if you have any further problems
